# -*- coding: utf-8 -*-
"""Nadadores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOAQWPxENvJfXZzBYt0UU-8vsqzdo9lT
"""

#Elabore um algoritmo que dada a idade de um nadador classifique-o em uma das seguintes categorias:

idade_do_nadador = int(input("Informe a idade do nadador?"))

if idade_do_nadador  >= 5 and idade_do_nadador <= 7 :
  print('Infantil_A')
elif idade_do_nadador >= 8 and idade_do_nadador <= 11 :
  print('Infantil_B')
elif idade_do_nadador >= 12 and idade_do_nadador <= 13 :
  print('Infantil_C')
elif idade_do_nadador >= 14 and idade_do_nadador <= 17 :
  print('Infantil_D')
elif idade_do_nadador == 18 :
  print('Adulto')
else:
  print ('Digite novamente')

